version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - evolution-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=EMAIL
      - PGADMIN_DEFAULT_PASSWORD=PASSWORD  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    links:
      - postgres
    networks:
      - evolution-net
    
  # redis:
  #   image: redis:latest
  #   networks:
  #     - evolution-net
  #   container_name: redis
  #   command: >
  #     redis-server --port 6379 --appendonly yes
  #   volumes:
  #     - evolution_redis:/data
  #   ports:
  #     - 6379:6379

  evolution_api:
    image: atendai/evolution-api:v2.1.0
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - evolution-net
    restart: always  # Add this line to ensure it restarts automatically
    command: tail -f /dev/null

volumes:
  postgres_data:
  pgadmin_data:
  # evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge